name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run:  echo "Hello World"|echo "This is second command run by using pipe."
      - name: Print goodbye
        run: echo "Done - bye"
